name: fluttery_framework
description: Provides all the functions and features needed for a typical production app.
homepage: https://www.andrioussolutions.com
repository: https://github.com/AndriousSolutions/fluttery_framework

version: 2.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  # https://pub.dartlang.org/packages/connectivity_plus
  connectivity_plus: ^3.0.0

  # https://pub.dev/packages/device_info_plus
  device_info_plus: ^8.0.0

  flutter:
    sdk: flutter

#  # https://pub.dev/packages/flutter_local_notifications
#  # Issues with flutter_local_notifications overridden to 9.7.1 below
#  flutter_local_notifications: ^9.0.0

  # To support for other languages other than US English localizations
  flutter_localizations:
    sdk: flutter

  # https://pub.dev/packages/flutter_material_color_picker/
  flutter_material_color_picker: ^1.0.0

  # https://pub.dev/packages/flutter_native_timezone/
  flutter_native_timezone: ^2.0.0

  flutter_test:
    sdk: flutter

  # https://pub.dev/packages/http/
  http: ^0.13.0

  # https://pub.dev/packages/i10n_translator/
  l10n_translator: ^4.0.0
#      path: ../../packages/l10n_translator

  # https://pub.dev/packages/package_info_plus
  package_info_plus: ^3.0.0

  # https://pub.dev/packages/path_provider
  path_provider: ^2.0.0

  # https://pub.dartlang.org/packages/prefs
  prefs: ^4.0.0
  #    path: ../../packages/prefs

  # https://pub.dev/packages/sizer
  sizer: ^2.0.0

  # https://pub.dartlang.org/packages/state_extended
  state_extended: ^2.0.0
#      path: ../../packages/state_extended

  # https://pub.dev/packages/timezone
  timezone: ^0.9.0

  # https://pub.dev/packages/unique_identifier
  unique_identifier: ^0.3.0

  # https://pub.dev/packages/universal_html/
  universal_html: ^2.0.0

  # https://pub.dev/packages/universal_platform
  universal_platform: ^1.0.0

  # https://pub.dartlang.org/packages/url_launcher
  # used in AppSettings.dart
  url_launcher: ^6.0.0
  url_launcher_web: ^2.0.0

  # https://pub.dev/packages/url_strategy
  url_strategy: ^0.2.0

  # https://pub.dartlang.org/packages/uuid
  uuid: ^3.0.0

#dependency_overrides:
#  flutter_local_notifications: 9.7.1

dev_dependencies:
  # Supply the example app for testing.
  fluttery_framework_example:
    path: example

  # Used during Continuous Integration
  integration_test:
    sdk: flutter
  #  # Needed here as well for testing
  #  flutter_test:
  #    sdk: flutter

#  # Setting up Lint Rules
#  # Most of the recommended lints directly implement the guidelines set out in Effective Dart:
#  # https://dart.dev/guides/language/effective-dart
#  # https://pub.dev/packages/pedantic
#  pedantic: ^1.10.0-nullsafety.3

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
