name: fluttery_framework
description: Provides all the functions and features needed for a typical production app.
homepage: https://www.andrioussolutions.com
repository: https://github.com/AndriousSolutions/fluttery_framework
issue_tracker: https://github.com/AndriousSolutions/fluttery_framework/issues?q=is:issue+is:open

version: 5.0.1+5

environment:
#  sdk: '>=2.19.0 <4.0.0'
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # https://pub.dartlang.org/packages/connectivity_plus
  connectivity_plus: ^6.0.5

  # https://pub.dev/packages/device_info_plus
  device_info_plus: ^10.1.2

  flutter:
    sdk: flutter

  # To support for other languages other than US English localizations
  flutter_localizations:
    sdk: flutter

  flutter_test:
    sdk: flutter

  # https://pub.dev/packages/go_router/
  go_router: ^14.2.7

  # https://pub.dev/packages/http/
  http: ^1.2.2

  # https://pub.dev/packages/i10n_translator/
  l10n_translator: ^4.1.4
#        path: ../../packages/l10n_translator

  # https://pub.dev/packages/package_info_plus
  package_info_plus: ^8.0.2

  # https://pub.dev/packages/path_provider
  path_provider: ^2.1.4

  # https://pub.dartlang.org/packages/prefs
  prefs: ^4.2.0
  #    path: ../../packages/prefs

  # https://pub.dev/packages/sizer
  sizer: ^3.0.3

  # https://pub.dartlang.org/packages/state_extended
  state_extended: ^5.0.0+2
#      path: ../../packages/state_extended

  # https://pub.dev/packages/timezone
  timezone: ^0.9.4

  # https://pub.dev/packages/universal_io
  universal_io: ^2.2.2

  # https://pub.dev/packages/universal_platform
  universal_platform: ^1.1.0

  # https://pub.dartlang.org/packages/url_launcher
  # used in AppSettings.dart
  url_launcher: ^6.3.0

  url_launcher_web: ^2.3.3

  # https://pub.dev/packages/url_strategy
  url_strategy: ^0.3.0

  # https://pub.dartlang.org/packages/uuid
  uuid: ^4.5.0

dev_dependencies:
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml`
  flutter_lints: ^4.0.0

  # Supply the example app for testing.
  fluttery_framework_example:
    path: example

  # Used during Continuous Integration
  integration_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
